name: Deploy to maven builds repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: builds repo workflow dispatch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: "buiawpkgew1",
              repo: "MavenBuilds",
              workflow_id: 'deploy.yml',
              ref: 'main',
            })
      
